version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq-cental
    ports:
      - "5673:5672"   # Maps Mac port 5673 to Container port 5672
      - "15673:15672" # Maps Mac port 15673 to Container port 15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    container_name: redis-cental
    ports:
      - "6379:6379"   # Standard Redis port
    volumes:
      - redis_data:/data
    networks:
      - app-network

volumes:
  rabbitmq_data:
  redis_data:

networks:
  app-network:
    driver: bridge
