version: '3.1'

services:
  postgresql:
    image: postgres:15
    container_name: postgres-db2
    restart: always
    ports:
      - "5435:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: table
