spring.application.name=rest-table-service
spring.jpa.hibernate.ddl-auto=none
server.port=1987

spring.sql.init.mode=always
# by passing error- schema.sql errors
spring.sql.init.continue-on-error=true
#spring.sql.init.data-locations=data.sql


