spring.application.name=rest-table-service
server.port=1987

# ========== DATABASE CONFIGURATION ==========
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5435/table
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ========== SQL SCRIPT BYPASS ==========
spring.sql.init.mode=always
spring.sql.init.continue-on-error=true

# ========== EVENT STREAM BROKER CONFIGURATION ==========
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5673
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.cloud.stream.rabbit.binder.nodes=localhost



# ========== Log ==========
logging.file.name=app.log

# ========== SPRING CLOUD STREAM FUNCTION SETTINGS ==========
spring.cloud.stream.function.autodetect=false

spring.cloud.function.definition=processCreationRequest;confirmTable

# =========================================================================
# BINDINGS FOR: processCreationRequest
# =========================================================================
spring.cloud.stream.bindings.processCreationRequest-in-0.destination=table--exchange
spring.cloud.stream.bindings.processCreationRequest-in-0.group=table-service-group

spring.cloud.stream.bindings.processCreationRequest-out-0.destination=table-confirmation-exchange

# =========================================================================
# BINDINGS FOR: confirmTable
# =========================================================================
spring.cloud.stream.bindings.confirmTable-in-0.destination=table-confirmation-exchange
spring.cloud.stream.bindings.confirmTable-in-0.group=confirm-table-group
