-- 1. Insert data only if the business keys do not already exist
INSERT INTO table_defination (table_id, capacity)
SELECT 'T1', 4 WHERE NOT EXISTS (SELECT 1 FROM table_defination WHERE table_id = 'T1');

INSERT INTO table_defination (table_id, capacity)
SELECT 'T2', 4 WHERE NOT EXISTS (SELECT 1 FROM table_defination WHERE table_id = 'T2');

INSERT INTO table_defination (table_id, capacity)
SELECT 'T3', 5 WHERE NOT EXISTS (SELECT 1 FROM table_defination WHERE table_id = 'T3');

INSERT INTO table_defination (table_id, capacity)
SELECT 'T4', 6 WHERE NOT EXISTS (SELECT 1 FROM table_defination WHERE table_id = 'T4');

INSERT INTO table_defination (table_id, capacity)
SELECT 'T5', 6 WHERE NOT EXISTS (SELECT 1 FROM table_defination WHERE table_id = 'T5');

INSERT INTO table_defination (table_id, capacity)
SELECT 'T6', 6 WHERE NOT EXISTS (SELECT 1 FROM table_defination WHERE table_id = 'T6');


-- 2. Map availability by looking up the primary key (id) generated by PostgreSQL
INSERT INTO table_availability (table_id, status, cust_id)
SELECT id, 'AVAILABLE', NULL 
FROM table_defination 
WHERE table_id IN ('T1', 'T2', 'T3', 'T4', 'T5', 'T6')
AND NOT EXISTS (
    SELECT 1 FROM table_availability ta 
    WHERE ta.table_id = table_defination.id
);
