server.port=7083

# Database Configuration
spring.docker.compose.enabled=false
spring.datasource.url=jdbc:postgresql://localhost:5433/front
spring.datasource.username=postgres
spring.datasource.password=password
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.cloud.compatibility-verifier.enabled=false

# ========== AMQP & RABBITMQ BINDER CONFIGURATION ==========
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5673
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

spring.cloud.stream.rabbit.binder.host=localhost
spring.cloud.stream.rabbit.binder.port=5672
spring.cloud.stream.rabbit.binder.username=guest
spring.cloud.stream.rabbit.binder.password=guest

# ========== SPRING CLOUD STREAM SETUP ==========
spring.cloud.stream.function.autodetect=false
spring.cloud.function.definition=processBrief;consumeAvailableTables;confirmReservation

# =========================================================================
# BINDINGS FOR: processBrief (Consumer of table-availability replies)
# Receives ReservationResponse from rest-table-service.processCreationRequest
# Queue Name here is table-confirmation-exchange, and the spring.cloud.stream.bindings."[my.output.binding.key]".destination
# =========================================================================
spring.cloud.stream.bindings.processBrief-in-0.destination=table-confirmation-exchange
spring.cloud.stream.bindings.processBrief-in-0.group=table-service-group

# =========================================================================
# BINDING FOR: outgoing reservation requests (sent via StreamBridge)
# =========================================================================
spring.cloud.stream.bindings.brief-request-out-0.destination=table--exchange

# =========================================================================
# BINDINGS FOR: confirmReservation
# Sends a table-lock/confirm request to rest-table-service.confirmTable,
# and receives the final confirmed response back on a SEPARATE exchange
# =========================================================================
spring.cloud.stream.bindings.confirmReservation-in-0.destination=table-final-confirmation-exchange
spring.cloud.stream.bindings.confirmReservation-in-0.group=table-service-group

spring.cloud.stream.bindings.confirmReservation-out-0.destination=table-confirm-request-exchange