server.port=7083

# Database Configuration
spring.docker.compose.enabled=false
spring.datasource.url=jdbc:postgresql://localhost:5433/restaurants
spring.datasource.username=postgres
spring.datasource.password=password
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.cloud.compatibility-verifier.enabled=false

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5673
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.database=0




# ========== Spring Cloud Stream Setup ==========

# Disable automatic scanning of functional beans
spring.cloud.stream.function.autodetect=false

# 1. Register your callback listener bean name
spring.cloud.function.definition=processBrief

# 2. Inbound Callback Binding (Listens for the response from Table Service)
spring.cloud.stream.bindings.processBrief-in-0.destination=table-confirmation-exchange
spring.cloud.stream.bindings.processBrief-in-0.group=table-service-group

# 3. Outbound Destination 1: Table Creation Flow (StreamBridge sends request here)
spring.cloud.stream.bindings.brief-request-out-0.destination=table-create-exchange

# 4. Outbound Destination 2: Table Confirmation Flow (Optional secondary output channel)
spring.cloud.stream.bindings.brief-request-out-1.destination=table-confirmation-exchange

